services:
  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: anant_ghee
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:6
    container_name: redis
    restart: always
    ports:
      - "6378:6379"

  # Migration service - runs once then stops
  migrate:
    build: .
    container_name: migrate
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    command: npx prisma migrate deploy
    restart: "no"

  nest-app:
    build: .
    container_name: nest_server
    restart: always
    depends_on:
      - db
      - redis
      - migrate
    ports:
      - "3000:3000"
    env_file:
      - .env
    command: npm run start:prod

volumes:
  pgdata: