version: '3.8'

services:
  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: anant_ghee
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:6
    container_name: redis
    restart: always
    ports:
      - "6379:6379"

  migrate:
    image: ajaygupta18/anant-ghee-backend:v1.0
    container_name: migrate
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql://postgres:root@db:5432/anant_ghee
    command: npx prisma migrate deploy
    restart: "no"

  nest-app:
    image: ajaygupta18/anant-ghee-backend:v1.0
    container_name: nest_server
    depends_on:
      - db
      - redis
      - migrate
    ports:
      - "3001:3000"
    environment:
      DATABASE_URL: postgresql://postgres:root@db:5432/anant_ghee
      JWT_ACCESS_TOKEN_SECRET: keytocreateaccesstoken
      JWT_REFRESH_TOKEN_SECRET: keytocreaterefreshtoken
      FRONTEND_BASE_URL: http://localhost:5173
      REDIS_HOST: redis
      REDIS_PORT: 6379
    command: npm run start:prod

volumes:
  pgdata:
